### ISSUE TITLE
Error when 'making' file

### ISSUE THREAD

**Issue by ghost** [aixxe/cstrike-basehook-linux#3]
[  6%] Building CXX object CMakeFiles/cstrike-basehook.dir/src/Basehook.cpp.o
In file included from /home/asiannoodles/Desktop/Sick Beats/src/Basehook.h:3:0,
                 from /home/asiannoodles/Desktop/Sick Beats/src/Basehook.cpp:21:
/usr/include/c++/6/cstddef:49:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
CMakeFiles/cstrike-basehook.dir/build.make:62: recipe for target 'CMakeFiles/cstrike-basehook.dir/src/Basehook.cpp.o' failed
make[2]: *** [CMakeFiles/cstrike-basehook.dir/src/Basehook.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cstrike-basehook.dir/all' failed
make[1]: *** [CMakeFiles/cstrike-basehook.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by aixxe** [comment]
This is a 32-bit project, you'll need the multilib variant of gcc to compile it.

**Comment by jalius** [comment]
`sudo apt-get install gcc-multilib && sudo apt-get imstall g++-multilib`
on ubuntu and debian

side note: thank you aixxe!
